#ibw_jobeet_homepage:
#    pattern:  /hello/{name}
#    defaults: { _controller: IbwJobeetBundle:Default:index }

IbwJobeetBundle_job:
        resource: "@IbwJobeetBundle/Resources/config/routing/job.yml"
        prefix:   /job